[package]
authors.workspace = true
categories.workspace = true
description = "rsql core library for creating a command line SQL interfaces"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_core"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
clap-stdin = { workspace = true, features = ["tokio"] }
clearscreen = { workspace = true }
colored = { workspace = true }
config = { workspace = true }
dark-light = { workspace = true }
dirs = { workspace = true }
indicatif = { workspace = true }
indoc = { workspace = true }
num-format = { workspace = true }
regex = { workspace = true }
rsql_drivers = { path = "../rsql_drivers", version = "0.14.0" }
rsql_formatters = { path = "../rsql_formatters", version = "0.14.0" }
rust-i18n = { workspace = true }
rustyline = { workspace = true, features = ["with-fuzzy"] }
serde_json = { workspace = true, features = ["preserve_order"] }
sqlparser = { workspace = true }
sys-locale = { workspace = true }
tempfile = { workspace = true }
termbg = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "process",
    "rt",
    "rt-multi-thread",
] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "tracing-log",
] }
unicode-width = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
mockall = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[features]
all = ["all-drivers", "all-formats"]
default = []
all-drivers = [
    "driver-duckdb",
    "driver-mariadb",
    "driver-mysql",
    "driver-postgres",
    "driver-postgresql",
    "driver-redshift",
    "driver-rusqlite",
    "driver-snowflake",
    "driver-sqlite",
    "driver-sqlserver",
]
driver-duckdb = ["rsql_drivers/duckdb"]
driver-libsql = ["rsql_drivers/libsql"]
driver-mariadb = ["rsql_drivers/mariadb"]
driver-mysql = ["rsql_drivers/mysql"]
driver-postgres = ["rsql_drivers/postgres"]
driver-postgresql = ["rsql_drivers/postgresql"]
driver-redshift = ["rsql_drivers/redshift"]
driver-rusqlite = ["rsql_drivers/rusqlite"]
driver-snowflake = ["rsql_drivers/snowflake"]
driver-sqlite = ["rsql_drivers/sqlite"]
driver-sqlserver = ["rsql_drivers/sqlserver"]
all-formats = [
    "format-ascii",
    "format-csv",
    "format-expanded",
    "format-html",
    "format-json",
    "format-jsonl",
    "format-markdown",
    "format-plain",
    "format-psql",
    "format-sqlite",
    "format-tsv",
    "format-unicode",
    "format-xml",
    "format-yaml",
]
format-ascii = ["rsql_formatters/ascii"]
format-csv = ["rsql_formatters/csv"]
format-expanded = ["rsql_formatters/expanded"]
format-html = ["rsql_formatters/html"]
format-json = ["rsql_formatters/json"]
format-jsonl = ["rsql_formatters/jsonl"]
format-markdown = ["rsql_formatters/markdown"]
format-plain = ["rsql_formatters/plain"]
format-psql = ["rsql_formatters/psql"]
format-sqlite = ["rsql_formatters/sqlite"]
format-tsv = ["rsql_formatters/tsv"]
format-unicode = ["rsql_formatters/unicode"]
format-xml = ["rsql_formatters/xml"]
format-yaml = ["rsql_formatters/yaml"]

[lints.clippy]
unwrap_used = "deny"

[package.metadata.docs.rs]
features = []
rustdoc-args = []
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name = "bench_main"
